name: Deploy when pushed to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: 164.92.246.13
          username: root
          password: imF(_2AcG#*fbBn
          script: bash .github/workflows/deploy.sh